### ISSUE TITLE
Update of dependencies

### ISSUE THREAD

**Issue by SenseException** [jonjomckay/quahog#15]
This library pretty outdated and needs an update of the following dependencies:
- PHP 5.6 and 7, also 5.6 as the minimal supported version
- Using newest Client library (#14)

Also some changes of standards would be nice:
- PSR-4 in Composer
- PHPUnit as dev requirement (Easier to test for devs when they know the version)
- Add missing PHP versions to `.travis-ci`

@jonjomckay Is this project still maintained?

**Comment by SenseException** [comment]
> Is this project still maintained?

Seems to me like "No".

**Comment by jonjomckay** [comment]
Hi @SenseException - sorry for the huge delay in replying. As you can probably tell, I've not been super on-the-ball with any of my PHP repositories recently as I now work for a Java & C# company (:see_no_evil:), and I therefore don't have much time to maintain this library.

I'd love to keep this going though, as I know it's a very useful library for a lot of people - would you be interested in being an (I guess) co-maintainer? I'm totally up for that!

**Comment by MassiveHiggsField** [comment]
I've made a pr with everything needed for this. But since i changed the namespaces to make them more composer friendly, this is a bc breaking change, so this fix should get a new major version.

**Comment by SenseException** [comment]
@jonjomckay The project is quite small with issues and PRs. I can support you, if you like.

**Comment by MassiveHiggsField** [comment]
same here

**Comment by SenseException** [comment]
I guess this can be handled as "solved".
