### ISSUE TITLE
Session mode broken over tcp

### ISSUE THREAD

**Issue by davidvanlaatum** [jonjomckay/quahog#21]
At least when using tcp I am seeing clam respond to commands when in session mode with a number prefix followed by the response. Problem is they arrive in two different tcp packets thus the read call in _receiveResponse only reads the number (eg "1:") and the next command you issue gets the actual response

**Comment by davidvanlaatum** [comment]
this also affects the stats command which doesn't always return everything in a single tcp packet

**Comment by SenseException** [comment]
Thank you for opening this issue. Do you want to provide a solution in a pull request for this?

**Comment by davidvanlaatum** [comment]
Ill have a go

**Comment by davidvanlaatum** [comment]
Pull request done. I also added a response timeout

**Comment by SenseException** [comment]
Thank you.

**Comment by SenseException** [comment]
PR #22 is now merged in `develop`. Thank you @davidvanlaatum.

**Comment by jonjomckay** [comment]
This is now released in v2.1.0 - it should appear in Packgist shortly!
