### ISSUE TITLE
Builds on Travis CI are very slow

### ISSUE THREAD

**Issue by jonjomckay** [jonjomckay/quahog#23]
The builds on Travis CI are really, really slow sometimes - occasionally taking 10 minutes to run. This is mostly because ClamAV takes an abnormally long amount of time to update - we could cache the `/var/lib/clamav` directory to try and speed this up in the future.

**Comment by MassiveHiggsField** [comment]
Good idea. While writing it, i got the notification that you already implemented it :+1:

**Comment by jonjomckay** [comment]
@MassiveHiggsField haha sorry! The build seems to be consistent around 2 minutes now which is a lot better - do you have any further recommendations?

**Comment by MassiveHiggsField** [comment]
No, not really. Just did a quick google check if it could have been done on the ClamAV side, startup parameter or something like that. But its absolutely fine this way :)

**Comment by jonjomckay** [comment]
Cool, I'll merge this in then :)
