### ISSUE TITLE
Explain start/stop Session methods in README

### ISSUE THREAD

**Issue by derikb** [jonjomckay/quahog#24]
It seems you need to use startSession() and endSession() if you want to send multiple commands through the socket (unless it's some kind of config issue on my end?). Would be nice to have that be in the documentation. I can do a pull request if you like.

**Comment by jonjomckay** [comment]
Thanks @derikb, we are missing documentation for that - a pull request would be happily received if you're up for doing one!

**Comment by SenseException** [comment]
It's good to have some missing additions to the readme file. `startSession()` and `endSession()` methods are merged. Thank you.
