### ISSUE TITLE
Update of PHPUnit to 5.7

### ISSUE THREAD

**Issue by SenseException** [jonjomckay/quahog#27]
Because quahog has the minimum PHP version of 5.6, we need to update PHPUnit and quahog's tests to a new version. PHPUnit 5.7 supports PHP 5.6 and is therefore the version of choice.

This is an easypick for developers, who are new to contributing to open source and want to be part it.

**Comment by jonjomckay** [comment]
Thanks @SenseException - that new PHPUnit API is very nice :)

**Comment by SenseException** [comment]
Thank you.
