### ISSUE TITLE
php 7.1

### ISSUE THREAD

**Issue by perfectwebtech** [jonjomckay/quahog#28]
is it support  php 7.1  clamav-php module ? 

or what is maximum version support ? i did try from sourceforce php-clamav module but

not suport  php 7.0 or 7.1 there is supoprt php5.4 and php 5.5  only

so is there way install php 7.0 clamav ?

**Comment by SenseException** [comment]
Quahog does not use the clamav-php module. It uses only the socket of the installed and running ClamAV service. You'll find information of the Quahog API and installation with composer in the README.md.

Here's the one for the current Quahog version.
https://github.com/jonjomckay/quahog/blob/v2.1.0/README.md
