### ISSUE TITLE
Socket operation failed: Broken pipe (SOCKET_EPIPE)

### ISSUE THREAD

**Issue by kesavankrishnan** [jonjomckay/quahog#30]
Am getting socket pipe broken error when  i try to scan more than 12 MB.
Could you please suggest me to overcome this

**Comment by veewee** [comment]
+1

**Comment by MassiveHiggsField** [comment]
Did that fix your problem @kesavankrishnan ?

**Comment by kesavankrishnan** [comment]
@MassiveHiggsField Yes, Actually i opened socket before file upload into server and then start scanning once uploaded. Socket broken issue happened due to the large files take more time and size. So i changed as like , open the socket and scanning process immediately .

**Comment by MassiveHiggsField** [comment]
👍 thanks @veewee

**Comment by kesavankrishnan** [comment]
Thanks @

**Comment by kesavan-fh** [comment]
@shireeshakalle Could you share the code to understand more on it.

**Comment by shireeshakalle** [comment]
Hi kesavan

please find the following code which I'm using

public static boolean isFileInfected(File file ) {
		boolean ifFileInfected = false;
		try {
			ifFileInfected = false;
			logger.debug("inside checkForclamAv.. ");

			// ClamAvScanner scanner = new ClamAvScanner("127.0.0.1", 3310);
			ClamAvScanner scanner = new ClamAvScanner("localhost", 3310, 5000);
			boolean isclamScannerAvailable = scanner.ping();

			logger.debug(isclamScannerAvailable + "is clam scanner Available");
			if (isclamScannerAvailable) {
				ScanResult result = scanner.scan(file);
				logger.debug("result.getStatus ....." + result.getStatus());
				if (result.getStatus() == ScanResult.Status.PASSED) {
					logger.debug("No Virus...");
					ifFileInfected = false;
				} else if (result.getStatus() == ScanResult.Status.INFECTED) {
					logger.debug("No Virus...");
					ifFileInfected = true;
				} else {
					ifFileInfected = true;
					logger.debug(
							"inside warning ......" + result.getStatus() + "Error message..." + result.getMessage());
				}
			}
		} catch (Exception e) {
			logger.error("error to connect..." + e.getMessage());
			e.printStackTrace();
		}
		return ifFileInfected;
	}
