### ISSUE TITLE
Socket operation failed: Broken pipe (SOCKET_EPIPE) ON Big file Scanning

### ISSUE THREAD

**Issue by kesavankrishnan** [jonjomckay/quahog#32]
We have received the "Socket operation failed: Broken pipe (SOCKET_EPIPE)" error when we scan 40 MB file with chunk size of 15 MB.

check my below code

`$this->socket = (new \Socket\Raw\Factory())->createClient(
                getenv('CLAMAV_SERVER')
            );
            $this->quahog = new \Xenolope\Quahog\Client($this->socket);

            //chunkSize (3 * 1024)
            $scannedResult = $this->quahog->scanLocalFile($storedPath, (15 * 1024));`

**Comment by MassiveHiggsField** [comment]
Try this https://github.com/jonjomckay/quahog/issues/30

**Comment by claudioflagbit** [comment]
In case the issue mentioned by @MassiveHiggsField doesn't help, can you please provide a PR with a failing test? You can create with vfsStream large in-memory files for your test.

If #30 was helpful and your problem solved, please close your issue.

**Comment by SenseException** [comment]
In case the issue mentioned by @MassiveHiggsField doesn't help, can you please provide a PR with a failing test? You can create with vfsStream large in-memory files for your test.

If #30 was helpful and your problem solved, please close your issue.

**Comment by kesavankrishnan** [comment]
@MassiveHiggsField  Could you please close this. Problem solved with StreamMaxLength
