### ISSUE TITLE
How to connect using IP:PORT using TCPv4, but not Unix socket?

### ISSUE THREAD

**Issue by tomekit** [jonjomckay/quahog#36]
Does this library support connecting over TCPv4 in order to use `scanstream`?
If so, would you mind showing an example? Much appreciated !

**Comment by robincsamuel** [comment]
@tomekit You can just do,

```
$socket = (new \Socket\Raw\Factory())->createClient('192.168.1.1:3310');
$quahog = new \Xenolope\Quahog\Client($socket, 30, PHP_NORMAL_READ);
$quahog->scanFile(...);
```

Passing `PHP_NORMAL_READ` as the mode as I got an error on PHP 7.3.

I hope that helps someone.

@jonjomckay Thanks for the package :)

**Comment by jonjomckay** [comment]
I've added a snippet the the `README.md` that should show others how to achieve this. Thanks all!
