### ISSUE TITLE
can you please make a tag of the latest changes?

### ISSUE THREAD

**Issue by dominikzogg** [jonjomckay/quahog#39]

**Comment by SenseException** [comment]
AFAIK there is no release plan yet.

@jonjomckay Did you plan something to release soon?

**Comment by jonjomckay** [comment]
Coming soon! My apologies for being absent from here for so long... life threw me some other priorities for a bit :sweat_smile:

**Comment by jonjomckay** [comment]
@dominikzogg [v3.0.0](https://github.com/jonjomckay/quahog/releases/tag/v3.0.0) has just been tagged and released!

**Comment by dominikzogg** [comment]
@jonjomckay ;-)
